"""
gen_seed.py — generates supabase/seed.sql from a race results CSV.

Usage:
    python scripts/gen_seed.py                          # uses default CSV
    python scripts/gen_seed.py "path/to/results.csv"   # custom CSV

The script reads the CSV, then outputs three INSERT blocks:
  1. INSERT INTO races    — one row per invocation (edit name/date/type/location)
  2. INSERT INTO athletes — one row per finisher
  3. INSERT INTO results  — joins back to athlete by name

Paste the output into the Supabase SQL Editor and run it.
"""

import csv
import sys
import io
import os

# ── Config ────────────────────────────────────────────────────────────────────

DEFAULT_CSV = os.path.join(
    os.path.dirname(__file__),
    "../data/Treeathlon Results 2026.csv",
)

RACE_NAME     = "Treeathlon 2026"
RACE_DATE     = "2026-01-01"
RACE_TYPE     = "Sprint"
RACE_LOCATION = "Santa Clara, CA"

# ── Helpers ───────────────────────────────────────────────────────────────────

def S(v):
    """SQL string literal, NULL if blank."""
    v = str(v).strip() if v else ""
    if not v:
        return "NULL"
    return "'" + v.replace("'", "''") + "'"

def N(v):
    """SQL integer literal, NULL if blank/non-numeric."""
    try:
        return str(int(str(v).strip()))
    except (ValueError, AttributeError):
        return "NULL"

def interval(t):
    """Convert H:MM:SS string to quoted HH:MM:SS interval, NULL if blank."""
    t = str(t).strip()
    if not t or t in ("0:00:00", "DQ"):
        return "NULL"
    parts = t.split(":")
    try:
        if len(parts) == 3:
            h, m, s = int(parts[0]), int(parts[1]), int(parts[2])
            return f"'{h:02d}:{m:02d}:{s:02d}'"
    except ValueError:
        pass
    return "NULL"

# ── Load CSV ──────────────────────────────────────────────────────────────────

csv_path = sys.argv[1] if len(sys.argv) > 1 else DEFAULT_CSV

rows = []
with open(csv_path, encoding="utf-8-sig", errors="replace") as f:
    reader = csv.DictReader(f)
    for row in reader:
        bib  = row.get("Bib", "").strip()
        chip = row.get("Chip Elapsed", "").strip()
        if not bib or not chip or chip == "DQ":
            continue
        # Sanitise names to ASCII (a few have encoding oddities in the CSV)
        row["Name"] = row["Name"].encode("ascii", "replace").decode("ascii")
        rows.append(row)

# ── Build SQL ─────────────────────────────────────────────────────────────────

out = io.StringIO()

def emit(*args, **kwargs):
    print(*args, **kwargs, file=out)

emit("-- ================================================================")
emit("-- Generated by scripts/gen_seed.py")
emit(f"-- Source: {os.path.basename(csv_path)}")
emit("-- Run this in the Supabase SQL Editor after applying schema.sql")
emit("-- ================================================================")
emit()

# 1. Race
emit("-- ── 1. Race ─────────────────────────────────────────────────────")
emit("INSERT INTO races (name, date, type, location) VALUES")
emit(f"  ({S(RACE_NAME)}, {S(RACE_DATE)}, {S(RACE_TYPE)}, {S(RACE_LOCATION)});")
emit()

# 2. Athletes
emit("-- ── 2. Athletes ─────────────────────────────────────────────────")
emit("INSERT INTO athletes (name, team, city, gender) VALUES")
athlete_vals = [
    f"  ({S(r['Name'])}, {S(r['Team Name'])}, {S(r['City'])}, {S(r['Gender'])})"
    for r in rows
]
emit(",\n".join(athlete_vals) + ";")
emit()

# 3. Results
emit("-- ── 3. Results ──────────────────────────────────────────────────")
emit("-- Assumes the race inserted above received id=1.")
emit("-- If you are adding a second race, change '1' to the correct race id.")
emit("INSERT INTO results")
emit("  (race_id, athlete_id, age_at_race, bib,")
emit("   swim, t1, bike, t2, run, chip_elapsed, overall_rank)")
emit("SELECT")
emit("  1 AS race_id,")
emit("  a.id AS athlete_id,")
emit("  v.age_at_race, v.bib,")
emit("  v.swim::INTERVAL,")
emit("  v.t1::INTERVAL,")
emit("  v.bike::INTERVAL,")
emit("  v.t2::INTERVAL,")
emit("  v.run::INTERVAL,")
emit("  v.chip_elapsed::INTERVAL,")
emit("  v.overall_rank")
emit("FROM (VALUES")

result_vals = [
    "  ({name}, {bib}, {age}, {swim}, {t1}, {bike}, {t2}, {run}, {chip}, {rank})".format(
        name = S(r["Name"]),
        bib  = r["Bib"].strip(),
        age  = N(r.get("Age", "")),
        swim = interval(r.get("Swim", "")),
        t1   = interval(r.get("T1", "")),
        bike = interval(r.get("Bike", "")),
        t2   = interval(r.get("T2", "")),
        run  = interval(r.get("Run", "")),
        chip = interval(r.get("Chip Elapsed", "")),
        rank = N(r.get("Overall Rank", "")),
    )
    for r in rows
]
emit(",\n".join(result_vals))
emit(") AS v(name, bib, age_at_race, swim, t1, bike, t2, run, chip_elapsed, overall_rank)")
emit("JOIN athletes a ON a.name = v.name;")

# ── Write output ──────────────────────────────────────────────────────────────

sql = out.getvalue()

output_path = os.path.join(os.path.dirname(__file__), "../supabase/seed.sql")
with open(output_path, "w", encoding="utf-8") as f:
    f.write(sql)

print(f"Written to {os.path.normpath(output_path)}")
print(f"  {len(rows)} athletes / results rows")
